#!/bin/bash

clamlog=/var/log/clamav/clamav2.log
truncate -s 0 $clamlog  
#files="--exclude=/boot/initrd.img* --exclude=/home/homefile --exclude=/tmpfile --exclude=/var/lib/clamav/*.cvd --exclude=/var/cache/apt/*.bin --exclude=/var/lib/apt/lists/archive* --exclude=/usr/lib/x86_64-linux-gnu/libicudata.so.66.1"
cronic /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 clamscan -ri / --exclude-dir=/proc --exclude-dir=/sys --exclude-dir=/dev --exclude-dir=/media --exclude-dir=/mnt -l $clamlog 
MALWARE=$(tail "$clamlog"|grep Infected|cut -d" " -f3) && if [[ "$MALWARE" -ne "0" ]]; then mail -s "Malware Found $(hostname)" $(cat ~/.env/EMAIL) <<< $(cat $clamlog); fi
