#!/bin/bash
sudo snap refresh &>/dev/null && snap list --all | awk '/disabled/{print $1, $3}' | while read name rev; do echo $name >> report; snap remove "$name" --revision="$rev"; done; echo $date >> report
#do snap remove "$name" --revision="$rev"; done

